# Generated by Django 4.0.2 on 2026-02-01 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='post_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
